### ISSUE TITLE
Hymn 218

### ISSUE THREAD

**Issue by TBuTcher71** [isax5/Hymnal-Xamarin#115]
218 chorus 

Should be

Like the stars of the morning,
His bright crown adorning,
They shall shine in their beauty,
Bright gems for His crown.

**Comment by isax5** [comment]
Thanks a lot
What hymn book are you talking about??

**Comment by TBuTcher71** [comment]
[cid:6240B1AD-F65B-45EF-8DFD-8B87178B4E6F-L0-001]

Does that help? In iOS

Regards Haydn Gerken
Yuneec Drones Australia
ABN: 92970209393<tel:92970209393>
180 Forest Home Rd,<x-apple-data-detectors://1/1>
Rathdowney QLD 4287<x-apple-data-detectors://1/1>
+61 4 1058 4575<tel:+61%204%201058%204575>
www.yuneecdronesaustralia.com.au<http://www.yuneecdronesaustralia.com.au/>
sales@yuneecdronesaustralia.com.au<mailto:sales@yuneecdronesaustralia.com.au>

On 19 Dec 2020, at 10:33 pm, isax5 <notifications@github.com> wrote:

﻿

Thanks a lot
What hymn book are you talking about??

**Comment by TBuTcher71** [comment]
There are actually quite a few mistakes in the hymnal... it looks like you may have just got the text from the hymns titles but not actually from the SDA hymnal as e we use different verses sometimes.



Regards Haydn Gerken
Yuneec Drones Australia
ABN: 92970209393<tel:92970209393>
180 Forest Home Rd,<x-apple-data-detectors://1/1>
Rathdowney QLD 4287<x-apple-data-detectors://1/1>
+61 4 1058 4575<tel:+61%204%201058%204575>
www.yuneecdronesaustralia.com.au<http://www.yuneecdronesaustralia.com.au/>
sales@yuneecdronesaustralia.com.au<mailto:sales@yuneecdronesaustralia.com.au>

On 19 Dec 2020, at 10:33 pm, isax5 <notifications@github.com> wrote:

﻿

Thanks a lot
What hymn book are you talking about??

**Comment by isax5** [comment]
We're fixing a few here
https://github.com/isax5/Hymnal-Xamarin/pull/116

Thanks for your help
