### ISSUE TITLE
Update to Xamarin 5

### ISSUE THREAD

**Issue by isax5** [isax5/Hymnal-Xamarin#123]
- [x] Json Newtonsoft
- [x] Check MVVMCross
- [x] Check other packages
- [x] Test DB
- [x] Test iOS
- [x] Test Android
- [x] Solve some Android issues
- [ ] Test Tizen
- [ ] AppleTV
- [ ] Update Dark mode support
- [x] Check native player
- [ ] Check languages support
- [ ] Check Tabbed page updates
- [ ] Check updates in Xamarin Community Toolkit

**Comment by adrielsand** [comment]
Anything I could help with? I can test some things if you want.

**Comment by isax5** [comment]
@adrielsand you can enter the testing program:
> Beta testing programs:

|Platform    |Link                                                                                                              |
|------------|------------------------------------------------------------------------------------------------------------------|
|Android     |Beta testers program in [PlayStore](https://play.google.com/store/apps/details?id=net.ddns.HimnarioAdventistaSPA) |
|iOS         |Public link for [TestFlight](https://testflight.apple.com/join/0zTExNbR) program                                  |

**Comment by danielbair** [comment]
iOS TestFlight link says... 
"This beta isn't accepting any new testers right now."

**Comment by isax5** [comment]
@danielbair 
I see, probably is because I didn't send any update the last 90 days,
Do you know  Xamarin?

**Comment by danielbair** [comment]
I have worked in MS .NET and VS C# before, but not recently. I installed Xamarin five years ago, but never did anything in it yet (last year I updated it to VS 2019). I have contributed to some C++ and Python projects but I have done most of my development in HTML/CSS/JS/PHP.

I don't know Xamarin, but I'm willing to learn.
