### ISSUE TITLE
Some hymn text inaccurate

### ISSUE THREAD

**Issue by granola7** [isax5/Hymnal-Xamarin#205]
Thanks for putting this app together - I've been enjoying it. I use the 1985 English hymnal and I noticed there are some differences in the text, mostly punctuation but also some spelling and words. If I sent you a diff, is that something you would find useful? Or a pull request; I'm new to GitHub, but I can try to figure it out.

**Comment by thebiblelover7** [comment]
Probably show the fixes, and maybe create a PR.
@isax5 What do you prefer?

**Comment by isax5** [comment]
Yeah, create a PR with the modifications
Send it to the last sprint's branch
